---
# tasks file for chinainit
- name: Set timezone to {{ timezone_name }}
  timezone:
    name: "{{ timezone_name }}"

- name: Change apt Sourcelist
  template:
    src: "{{sources_list}}.sources.list"
    dest: /etc/apt/sources.list
    backup: yes
    mode: u=rw,g=r,o=r
  when: ansible_facts['os_family'] == 'Debian'
  
- name: Update repositories cache
  apt:
    update_cache: yes
    cache_valid_time: 86400